stages:
  - build
  - run

image: docker:latest

services:
  - docker:19.03.1-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build . --file Dockerfile --tag node-demo:$(date +%s) --tag node-demo:v1
    - hostname

getHostname:
  stage: run
  script:
    - hostname

#     # have to push to repo ,then pull 
# run docker:
#   stage: run
#   script:
#     - docker run -p 8080:8080 -d node-demo:v1