stages:
  - build
  - run

image: docker:latest

services:
  - docker:19.03.1-dind

before_script:
  - docker info

build_and_run:
  stage: build
  script:
    - docker build . --file Dockerfile --tag node-demo:$(date +%s) --tag node-demo:v1
    - docker run -p 8080:8080 -d node-demo:v1