name: Test Pipeline

on: 
  push:
    branches: 
      - master
jobs:

  build_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node-demo:$(date +%s)
    - name: get hostname
      run: hostname


  # run_image:
  #   runs-on: ubuntu-latest