name: Node Demo Pipeline 
on: 
  push:
    branches: 
      - master
jobs:

  build_run_image:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node-demo:$(date +%s) --tag node-demo:v1
    - name: Run image
      run: docker run -p 8080:8080 -d node-demo:v1