name: Test Pipeline

on: 
  push:
    branches: 
      - master
jobs:

  build_image:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node-demo:$(date +%s) --tag node-demo:v1
    - name: Get hostname
      run: hostname

  run_image:
    runs-on: ubuntu-latest
    steps:
    - name: Run image
      run: docker run -p 49160:8080 -d node-demo:v1
    - name: Get hostame Again
      run: hostname
